### ISSUE TITLE
[Todo] Bare-minimum todo list

### ISSUE THREAD

**Issue by jeongbeen2** [jeongbeen2/coronaga#4]
### 구축
- [ ] Javascript -> Typescript 변경
- [ ] any type 없이 변경하기
- [ ] 자체 서버 도입
- [ ] aws 연결

### 서비스
- [ ] 로그인 기능
- [ ] 잔여 백신 기능
- [ ] 코로나 차트 도입
